---
- name: Configure remote logging for all defined rhel machines
  hosts: all,!audisp_server
  gather_facts: no
  roles:
    - audisp-client

- name: Configure centralized logging server for all defined rhel machines
  hosts: audisp_server
  gather_facts: no
  roles:
    - audisp-server
